name: Publish ndjson to pub.dev
run-name: >-
  [ndjson] package publish (${{ github.ref_name }}) triggered by @${{ github.actor }}

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Run Dart analyzer
        run: dart analyze --fatal-infos

      - name: Publish
        run: dart pub publish --force
